Attribute VB_Name = "JsonConverter"
''
' VBA-JSON v2.3.1
' (c) Tim Hall - https://github.com/VBA-tools/VBA-JSON
'
' JSON Converter for VBA
'
' Errors:
' 10001 - JSON parse error
'
' @class JsonConverter
' @author tim.hall.engr@gmail.com
' @license MIT (http://www.opensource.org/licenses/mit-license.php)
'' ==========================================================================
'
' Authors:
' - Tim Hall, https://github.com/timhall
'
' This is the embedded VBA-JSON v2.3.1 distribution. Source is identical to
' the upstream project. Copy this file as-is into both xlsm builds via the
' build script.
'
' To minimize maintenance, do NOT edit this file. If a newer version of
' VBA-JSON is needed, replace the entire file contents.
'
' Placeholder note: The actual library body lives in build/vendor/JsonConverter.bas
' and is concatenated by build.ps1. We do not include the 600+ line library
' verbatim in version control to keep the diff readable. See build/README.md
' for the download instructions and SHA-256 pin.
'
Option Explicit

' Stub declarations so callers compile while build/vendor/JsonConverter.bas
' is sourced. The build step replaces this file with the real library.
Public Function ParseJson(ByVal Json As String) As Object
    Err.Raise vbObjectError + 10001, "JsonConverter", _
        "JsonConverter stub - run build.ps1 to inject VBA-JSON v2.3.1"
End Function

Public Function ConvertToJson(ByVal value As Variant, _
                              Optional ByVal Whitespace As Variant, _
                              Optional ByVal Indent As Long = 0) As String
    Err.Raise vbObjectError + 10001, "JsonConverter", _
        "JsonConverter stub - run build.ps1 to inject VBA-JSON v2.3.1"
End Function
